language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
# command to install dependencies
install:
  - pip install .
before_script:
  - chmod 777 ./tests/do_test.sh
# command to run tests
script: ./tests/do_test.sh

before_install:
  - pip install codecov
after_success:
  - codecov